### ISSUE TITLE
Bug: Error message about requiring .Net 9.0.4 when .Net 9.0.8 is installed

### ISSUE THREAD

**Issue by Dragon-32** [Reloaded-Project/Reloaded-II#684]
**Describe the Bug**
Updating .Net to 9.0.8 means that Reloaded throws an error on start-up about needing 9.0.4 and won;t launch P5R

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [MS' download page](https://dotnet.microsoft.com/en-us/download/dotnet/9.0) and update desktop runtimes, x86 and x64, to 9.0.8
2. Launch Reloaded-II
3. Missing Requirements dialog about not having 9.0.4 installed
4. Close requirements dialog and Launch Application for P5R.exe fails silently

**Expected Behaviour**
I'd expect 9.0.8 to fulfil requirements.

**Additional Context**
A process ID briefly appears in Processes when attempting to Launch Application.

No .log is created in either \LauncherErrors or \Logs

9.0.8 was released on 5th August 2025

I'm updating .Net trying to fix an error
```
Application: P5R.exe
CoreCLR Version: 9.0.425.16305
.NET Version: 9.0.4
Description: The process was terminated due to an unhandled exception.
Stack:
   at p5rpc.lib.Components.FlowCaller.MainLoop()
```

**Comment by Sewer56** [comment]
Versions 9.0.5 - 9.0.7 had a breaking runtime bug which would cause games to crash.

So the actual Reloaded loader was set to enforce 9.0.4. That is not a bug.

-----

The underlying issue was fixed in 9.0.8, but I just haven't updated the software yet.

The built-in runtime updater (as part of setup) is borked, so concern is, it could prompt the user to update to 9.0.8, and get stuck in the process, requiring the user to manually update.

I did make a patch to a related bug, but I'm not sure if that patch fixed it.

**Comment by Sewer56** [comment]
As for your runtime issue, consider posting the list of mods you have enabled. Clicking 'Save Mod Set' and uploading the resulting .json would be enough.

@AnimatedSwine37 would probably know some more from there on, since their mod was the one in the error.

**Comment by Dragon-32** [comment]
Thanks for such a quick reply.

I wasn't aware there were such problems with 9.0.5 thru 9.0.7, I can see why my hypothetical simplistic ≥ 9.0.4 check wouldn't work

.json of the modlist
[Mods_2025-08-24.json](https://github.com/user-attachments/files/21959128/Mods_2025-08-24.json)

Error I posted is thrown on the evening of 3rd August, Joker receives a SMS from Yusuke and the error's thrown before the txt message from him is fully rendered, just the dialog shows.

**Comment by Dragon-32** [comment]
Reinstalled the 9.0.4 runtimes on top of 9.0.8 and Reloaded-II will start (title screen shows .Net as 9.0.8) and launch P5R.

Thanks for your help. Hopefully you're able to wrestle the problems with updating to 9.0.8 or later into submission.

Problematic mods look like "P5R Unhardcoded Toolkit" with "Colored Chat Icon Backgrounds", disabling those two lets the text conversation with Yusuke actually appear.

I've added an Issue to https://github.com/Secre-C/P5R-Unhardcoded-Toolkit

**Comment by AnimatedSwine37** [comment]
I think that's a sort of known issue but it's good that you've made an actual issue for it. 
When the game updated from version 1.0.3b to 1.0.4 the code changed substantially and broke a lot of mods. Pretty much everything has been updated by now but a few things remain. I think unhardcoded toolkit might be one of those ones that wasn't fully fixed.

Also fwiw `p5rpc.lib` showing up in the stack trace doesn't necessarily mean anything. To inject flowscript calls in a way that doesn't mess with other ones I hooked one of the game's main loop functions. It causes a lot of the game's other code to run so if something called by it breaks, my mod can end up in the stack trace even though it had nothing to do with it. (Not to say that it's impossible that there's a problem with the mod lol)

**Comment by Dragon-32** [comment]
Thanks, AnimatedSwine37

I think this can be closed from a Reloaded-II point of view. Hopefully the .Net issue will be resolved in the near future.
